name: kokotan
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+6

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path_provider:
  url_launcher: ^6.1.11
  excel: ^4.0.3
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences:
  introduction_screen: ^3.1.14
  audioplayers: ^6.0.0
  clock: ^1.1.1
  fake_async: ^1.3.1
  fl_chart: ^0.69.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_hooks: ^0.18.0
  webview_flutter: ^4.0.7  
  image_picker: ^0.8.7+4 
  flutter_image_compress: ^1.1.0
  vibration: ^1.7.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  desktop_drop: ^0.5.0
  super_drag_and_drop: ^0.8.24
  flutter_markdown: ^0.6.10
  auto_size_text: ^3.0.0
  share_plus: ^10.1.2


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16



  flutter_lints: ^4.0.0
  test: ^1.24.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"

flutter_native_splash:
  image: "assets/images/sp_icon.png"
  color: "FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/add-picture.png
    - assets/db/dev_kokotan_list.xlsx
    - assets/images/intro_1.png
    - assets/images/intro_2.png
    - assets/images/intro_3.png
    - assets/images/intro_4.png
    - assets/images/OK.png
    - assets/images/yoyuu.png
    - assets/images/bimyou.png
    - assets/images/oboenaosu.png
    - assets/images/humor_otsukare_1.png
    - assets/images/sp_icon.png
    - assets/images/humor_column_1.png
    - assets/images/humor_column_2.png
    - assets/images/humor_column_3.png
    - assets/images/humor_column_4.png
    - assets/images/humor_column_5.png
    - assets/images/humor_column_6.png
    - assets/images/humor_home_1.png
    - assets/images/humor_home_2.png
    - assets/images/humor_home_3.png
    - assets/images/humor_home_4.png
    - assets/images/humor_home_5.png
    - assets/images/humor_home_6.png
    - assets/images/humor_home_7.png
    - assets/images/humor_home_8.png
    - assets/images/humor_home_9.png
    - assets/images/humor_otsukare_1.png
    - assets/images/humor_otsukare_2.png
    - assets/images/humor_otsukare_3.png
    - assets/images/humor_otsukare_4.png
    - assets/images/humor_otsukare_5.png
    - assets/images/humor_otsukare_6.png
    - assets/images/humor_otsukare_7.png
    - assets/images/humor_otsukare_8.png
    - assets/images/humor_otsukare_9.png
    - assets/images/humor_otsukare_10.png
    - assets/images/humor_otsukare_11.png
    - assets/images/humor_otsukare_12.png
    - assets/images/humor_otsukare_13.png
    - assets/images/humor_otsukare_14.png
    - assets/images/humor_otsukare_15.png
    - assets/images/humor_otsukare_16.png


  fonts:
    - family: ZenMaruGothic
      fonts:
        - asset: assets/fonts/ZenMaruGothic-Regular.ttf
        - asset: assets/fonts/ZenMaruGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenMaruGothic-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenMaruGothic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenMaruGothic-Black.ttf
          weight: 900